# Pre-commit configuration for FEMA USAR MCP Server
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        files: ^fema_usar_mcp/
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports, --show-error-codes]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
        additional_dependencies: ["bandit[toml]"]
        exclude: ^tests/

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.4
    hooks:
      - id: poetry-check
        files: ^pyproject\.toml$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, json, markdown]
        exclude: ^(\.github/workflows/.*\.yml|resources/.*)$

  - repo: local
    hooks:
      - id: pytest-unit
        name: pytest-unit
        entry: uv run pytest tests/ -m "unit" --tb=short -q
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push]

      - id: security-check
        name: security-check
        entry: bash -c 'uv add --group dev safety > /dev/null 2>&1; uv run safety check'
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push]

# Configuration for pre-commit.ci (if using)
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [pytest-unit, security-check]  # Skip slow hooks in CI
  submodules: false