app = "mcp-fema-usar"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder-jammy-base:latest"

[env]
  PORT = "8000"

[processes]
  app = "python server.py"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"

  [[services.http_checks]]
    path = "/"
    interval = "15s"
    timeout = "2s"
